<center><h1>Multi-Layer Perceptron Classifier</h1></center>

## Summary:

1. [Introduction](#introduction)

2. [Using the Classifier](#using_classifier)

# 1. Introduction <a class="anchor" id="introduction"></a>

The Multi-layer Perceptron (MLP) algorithm...

# 2. Using the classifier <a class="anchor" id="using_classifier"></a>

In [1]:
# Import the toolbox and its modules from the parent folder

import sys
sys.path.insert(0,'..')

from toolbox.learning.neural_networks.supervised.models.mlp import MultiLayerPerceptron
from toolbox.preprocessing.encoding import dummie2multilabel
from toolbox.evaluation.classifiers import confusion_matrix, compute_indices

# Import Auxiliary Libraries

import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.datasets import load_digits
from sklearn.preprocessing import MinMaxScaler


In [8]:
# DataSet

# Import digits recognition dataset (from sklearn)

X, y = load_digits(return_X_y=True)
X_tr, X_ts, y_tr, y_ts = train_test_split(X, y, test_size=0.4, random_state=2020)

# Scaling features (from sklearn)

scaler = MinMaxScaler()
scaler.fit(X_tr)
X_tr_norm = scaler.transform(X_tr)
X_ts_norm = scaler.transform(X_ts)

# Get number of attributes and classes

p = X_tr.shape[1]
n_samples_tr = X_tr.shape[0]
n_samples_ts = X_ts.shape[0]
n_classes = len(np.unique(y_tr))

# Reshape outputs

y_tr = y_tr.reshape((n_samples_tr,1))
y_ts = y_ts.reshape((n_samples_ts,1))

y_tr2 = np.zeros((n_samples_tr,n_classes))
y_ts2 = np.zeros((n_samples_ts,n_classes))

for i in range(n_samples_tr):
    y_tr2[i,y_tr[i]] = 1
for i in range(n_samples_ts):
    y_ts2[i,y_ts[i]] = 1

print('Number of Samples, Attributes and Classes:')
print(n_samples_tr,p,n_classes)
print(X_tr.shape)
print(y_tr.shape)
print(X_ts.shape)
print(y_ts.shape)
print(y_tr2.shape)
print(y_ts2.shape)
print(y_tr2[0:5,:])
print(y_ts2[0:5,:])

Number of Samples, Attributes and Classes:
1078 64 10
(1078, 64)
(1078, 1)
(719, 64)
(719, 1)
(1078, 10)
(719, 10)
[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
[[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]


In [ ]:
# MLP CLassifier

NPL = [p, 4, n_classes]

mlp = MultiLayerPerceptron()

mlp.fit(X=X_tr_norm, Y=y_tr2, Xv=X_tr, Yv=y_tr2, NPL=NPL, epochs=20, n_batches=1, 
        alpha=1e-2, decay=0, momentum=0, l2=0, dropout_percent=0)

y_mlp = mlp.predict(X_ts)[-1]


In [4]:
print(y_mlp[:,0:5])

[[1.44326405e-012 3.01497419e-032 3.21931740e-044 1.00587856e-041
  1.00000000e+000]
 [4.59001630e-078 8.92628838e-147 9.40758924e-070 1.00000000e+000
  4.41917680e-203]
 [1.12484884e-051 1.15480513e-144 1.67969630e-150 3.16511851e-096
  2.63327718e-070]
 ...
 [1.51007312e-021 7.65141296e-037 7.12987827e-044 1.67963032e-052
  1.81262908e-009]
 [1.00000000e+000 5.36663760e-159 6.08503706e-051 3.76364974e-026
  3.18528991e-128]
 [8.15123172e-036 3.09793473e-037 1.76371690e-068 2.03245703e-020
  1.50666607e-029]]
